# Generated by Django 5.0.4 on 2024-05-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustomachGestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proveedor_nombre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proveedor_telefono',
        ),
        migrations.AddField(
            model_name='equipo',
            name='informacion_proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appDeustomachGestion.proveedor'),
            preserve_default=False,
        ),
    ]
