# Generated by Django 5.0.4 on 2024-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustomachGestionEquipos', '0002_rename_empleados_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
