# Generated by Django 5.0.4 on 2024-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustomachGestionEquipos', '0003_alter_empleado_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='empleado_asignado',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
